name: Build APK Musik Spy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip curl
        pip install --upgrade pip
        pip install cython buildozer==1.5.0

    - name: Install Android command line tools
      run: |
       mkdir -p $HOME/android-sdk/cmdline-tools
       cd $HOME/android-sdk/cmdline-tools
       curl -O https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
       unzip -q commandlinetools-linux-9477386_latest.zip
       mv cmdline-tools latest
       export ANDROID_HOME=$HOME/android-sdk
       export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
       yes | sdkmanager --licenses
       sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
    
    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug
