name: Build APK Musik Spy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip curl
        pip install --upgrade pip
        pip install cython buildozer==1.5.0

    - name: Install Android SDK packages
      run: |
        export ANDROID_HOME=/home/runner/android-sdk
        /home/runner/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3"
        
    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug
