name: Build Kivy APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install buildozer cibuildwheel
          sudo apt-get update
          sudo apt-get install -y python3-dev openjdk-8-jdk unzip zlib1g-dev zip libncurses5

      - name: Initialize buildozer environment
        run: buildozer init

      - name: Copy buildozer.spec
        run: |
          mv buildozer.spec buildozer.spec
          ls -lah

      - name: Build debug APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: musikspy-apk
          path: bin/*.apk
