name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget curl libz-dev
          pip install cython==0.29.36 buildozer

      - name: Set up Apache ANT manual
        run: |
          mkdir -p ~/.buildozer/android/platform
          cp -r tools/apache-ant-1.9.4 ~/.buildozer/android/platform/apache-ant-1.9.4

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: musik-spy-debug.apk
          path: bin/*.apk
