name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget curl libz-dev
          pip install cython==0.29.36 buildozer

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/.android/cmdline-tools
          cd $HOME/.android/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip tools.zip -d tools
          export PATH=$HOME/.android/cmdline-tools/tools/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        
      - name: Set up Apache ANT manual
        run: |
          mkdir -p ~/.buildozer/android/platform
          cp -r tools/apache-ant-1.9.4 ~/.buildozer/android/platform/apache-ant-1.9.4

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: musik-spy-debug.apk
          path: bin/*.apk
