name: Build APK Musik Spy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip curl
        pip install --upgrade pip
        pip install cython buildozer==1.5.0

    - name: Download and Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip sdk-tools.zip -d latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

    - name: Accept SDK Licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager --update

    - name: Install SDK Components
      run: |
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Set ENV for Buildozer
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musik-spy.apk
        path: bin/*.apk
