name: Build Kivy APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-8-jdk python3-pip build-essential git python3-setuptools python3-wheel libncurses5-dev
          pip install cython
          yes | sdkmanager --licenses
          
      - name: Install buildozer
        run: |
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: musikspy-apk
          path: bin/*.apk
