name: Build APK Musik Spy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.home }}/android-sdk
      PATH: ${{ runner.home }}/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip curl
        pip install --upgrade pip
        pip install cython buildozer==1.5.0

    - name: Download and Install Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip sdk.zip -d latest

    - name: Accept SDK Licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install SDK Components
      run: |
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build APK
      run: |
        buildozer android debug
